Algoritmo "MAIO_10"
// 
//  
// Descricao   : Programa que verifica se o valor da variavel e maior que 10.
// Autor(a)    : Alex Nere Silva
// Data atual  : 7/9/2021
Var
// Secao de Declaracoes das variaveis

   A, B, X : real


Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...

 escreva("Digite o valor de A: ")
 leia(A)
 escreva("Digite o valor de B: ")
 leia(B)

 X <- A + B

 se X > 10 entao
    escreval("A soma entre ",A," e ",B," e igual a: ",X)
 fimse

Fimalgoritmo