Algoritmo "VALOR_QUADRADO"
// 
//  
// Descrição   : Apresentar a exponenciação de um valor inteiro.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/3/2021
Var
// Seção de Declarações das variáveis 
   A : inteiro
   RESULTADO : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um valor inteiro: ")
   leia(A)
   RESULTADO <- A^2
   escreva("A exponenciação de ",A," é igua a: ", RESULTADO)

Fimalgoritmo