Algoritmo "VALOR_QUADRADO"
// 
//  
// Descricao   : Apresentar a exponenciacao de um valor inteiro.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/3/2021
Var
// Secao de Declaracoes das variaveis 
   A : inteiro
   RESULTADO : real

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc... 
   escreva("Digite um valor inteiro: ")
   leia(A)
   RESULTADO <- A^2
   escreva("A exponenciacao de ",A," e igua a: ", RESULTADO)

Fimalgoritmo