Algoritmo "CONVERSOR"
// 
//  
// Descricao   : Programa que faz a leitura em grau celsios e apresenta em
//               fahrenheit.
// Autor(a)    : Alex Nere Silva
// Data atual  : 25/3/2021
Var
// Secao de Declaracoes das variaveis 
   C, F : REAL

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...

    escreva("Digite o valo em graus celsios: ")
    LEIA (C)
    F <- (9*C+160)/5
    escreval (C," graus celsios em fahrenheit e igual a: ",F," fahrenheit")

Fimalgoritmo