Algoritmo "CALCULO_CIRCUNFERENCIA"
// 
//  
// Descricao   : Calcula a area de uma circunferencia.
// Autor(a)    : Alex Nere Silva
// Data atual  : 8/4/2021
Var
// Secao de Declaracoes das variaveis 
   A, R : real

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc... 
   escreva("Digite o valor do raio: ")
   leia(R)
   A <- PI * R ^ 2
   escreva("A area do circulo e de: ",A)

Fimalgoritmo