Algoritmo "CONVERSOR"
// 
//  
// Descricao   : Fahrenheit convertida em graus Celsius.
// Autor(a)    : Alex Nere Silva
// Data atual  : 26/3/2021
Var
// Secao de Declaracoes das variaveis 
   C, F : REAL

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...
   
   escreva("Leia o valor de F: ")
   leia (F)
   C <- ((F-32)*5)/9
   escreva (F," Fahrenheit convertidos em graus é igual a: ",C)

Fimalgoritmo