Algoritmo "CALCULO_CIRCUNFERENCIA"
// 
//  
// Descrição   : Calcula a área de uma circunferência.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/4/2021
Var
// Seção de Declarações das variáveis 
   A, R : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite o valor do raio: ")
   leia(R)
   A <- PI * R ^ 2
   escreva("A área do circulo é de: ",A)

Fimalgoritmo